<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>

<div class="menu-cart-container">
    <div id="minicart-content-wrapper" class="cart-content" data-bind="scope: 'minicart_content'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
    <?= $block->getChildHtml('minicart.addons') ?>

    <script>
        require(['jquery'], function ($) {
            $('a.action.showcart').click(function() {
            return
            });
        });
    </script>
</div>