<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="custom-footer-links-container" >
    <ul class="custom-footer-links"> <p>CUSTOMER SERVICE </p>
        <li class="custom-footer-link"><a href="#">Support</a></li>
        <li class="custom-footer-link"><a href="#">Replacement</a></li>
        <li class="custom-footer-link"><a href="#">Shipping</a></li>
        <li class="custom-footer-link"><a href="#">FAQs</a></li>
    </ul>

    <ul class="custom-footer-links"> <p>Company</p>
        <li class="custom-footer-link"><a href="#">Our Story</a></li>
        <li class="custom-footer-link"><a href="#">Locations</a></li>
        <li class="custom-footer-link"><a href="#">Blog</a></li>
    </ul>
</div>
