<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="menu-icon-container" >
    <span class="menu-icon"></span>
    <a class="menu-label">
        MENU
    </a>
</div>

<script type="text/x-magento-init">
{
    ".menu-icon-container":{
        "Magento_Theme/js/displayMenu" :{
            "target": "menu-top-links-container"
        }
    }
}
</script>