<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="menu-icon-container" >
    <div class="menu-icon">
        &#9776;
    </div>
    <p class="menu-label">
        MENU
    </p>
</div>

<script type="text/x-magento-init">
{
    ".menu-icon-container":{
        "Magento_Theme/js/displayMenu" :{
            "target": "menu-top-links-container"
        }
    }
}
</script>