<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<div class="search-icon-container"  >
    <span class="search-icon"></span>
    <a class="search-label">
        SEARCH
    </a>
</div>

<script type="text/x-magento-init">
{
    ".search-icon-container":{
        "Magento_Theme/js/displayMenu" :{
            "target": "menu-search-container"
        }
    }
}
</script>

