<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="social-links-footer" >
   <a href="#" class="footer-social-link" id="facebook-container">
       <span id="icon-facebook"></span>
    </a>
   <a href="#" class="footer-social-link" id="twitter-container">
        <span id="icon-twitter"></span>
    </a>
   <a href="#" class="footer-social-link" id="instagram-container">
        <span id="icon-instagram"></span>
    </a>
   <a href="#" class="footer-social-link" id="youtube-container">
        <span id="icon-youtube"></span>
    </a>
</div>
