<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
?>

<?php if ($block->canShowBlock()) : ?>
    <div class="block filter">



        <div class="block-content filter-content">

            <?php $wrapOptions = false; ?>
            <div class="filter-container">

                <?php foreach ($block->getFilters() as $filter) : ?>
                    <?php if (!$wrapOptions) : ?>
                        <dl class="filter-options" id="narrow-by-list">
                        <?php $wrapOptions = true;
                    endif; ?>
                    
                        <?php if ($filter->getName() == "Price" || $filter->getName() == "Size" || $filter->getName() == "Color") : ?>
                            <?php if ($filter->getItemsCount()) : ?>
                                
                                
                                <div class="<?= $block->escapeHtmlAttr($filter->getName()) ?>-filter-option catalog-filter option">
                                    <dt role="heading" aria-level="3" class="filter-options-title"><?= $block->escapeHtml(__($filter->getName())) ?> :</dt>
                                    <dd class="filter-options-content"><?= /* @noEscape */ $block->getChildBlock('renderer')->render($filter) ?></dd>
                                </div>
                                
                            <?php endif; ?>
                        <?php endif; ?>
                        
            
                <?php endforeach; ?>
            </div>
            <?php if ($wrapOptions) : ?>
                </dl>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>

<!-- Magento after moving the toolbar plays it back to its old place so the directory page has 2 toolbars  -->
<!-- More info https://alanstorm.com/why-you-cant-remove-the-productlisttoolbar/  -->
<script type="text/x-magento-init">
{
    "*":{
        "Magento_LayeredNavigation/js/removeSecondToolbar" :{
        }
    },

    ".filter-options":{
        "Magento_LayeredNavigation/js/showFilters" :{
            "filters": ["Size-filter-option", "Price-filter-option", "Color-filter-option"]
        }
    }
}
</script>